import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { HierarchyPage } from '../pages/HierarchyPage';

test.describe('FaceLink Hierarchy Tests', () => {
  let hierarchyPage: HierarchyPage;

  test.beforeEach(async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.navigate();
    await loginPage.login();
    await page.waitForURL('**/dashboard');
    
    hierarchyPage = new HierarchyPage(page);
    await hierarchyPage.navigate();
    await page.waitForLoadState('networkidle');
  });

  test('should load Hierarchy elements correctly', async ({ page }) => {
    // Basic structural checks
    await expect(hierarchyPage.sidebar.hierarchyLink).toBeVisible();
    
    // Check Hierarchy core controls
    await expect(hierarchyPage.companyBtn).toBeVisible();
    
    // Check for hierarchy nodes generated by mock state
    await expect(hierarchyPage.groupNode).toBeVisible();
  });
});
